---
# tasks file for memcached
# Create k8s resources 
- name: Create resources for deployment
  k8s:
    state: present
    namespace: default
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: pdb.yaml.j2
    - name: statefulset.yaml.j2
    - name: svc.yaml.j2

