---
# defaults file for memcached

# Everything Below this line was inserted by helmExport

## Memcached image and tag
## ref: https://hub.docker.com/r/library/memcached/tags/
##
image: memcached:1.5.12-alpine

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# image_pull_policy:
#

## Replica count
replica_count: 3

name: memcached
version: 0.0.1

## Pod disruption budget minAvailable count
## Ensure this value is lower than replica_count in order to allow a worker
## node to drain successfully
pdb_min_available: 2

## Select _anti_affinity as either hard or soft, default is hard
_anti_affinity: "hard"

memcached:
  ## Various values that get set as command-line flags.
  ## ref: https://github.com/memcached/memcached/wiki/ConfiguringServer#commandline-arguments
  ##
  max_item_memory: 64
  verbosity: v
  extended_options: modern

## StatefulSet or Deployment
kind: StatefulSet

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 64Mi
    cpu: 50m

## Memcached pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
security_context:
  enabled: true
  fs_group: 1001
  run_as_user: 1001

metrics:
  ## Expose memcached metrics in Prometheus format
  enabled: false

  ## Memcached exporter image and tag
  image: quay.io/prometheus/memcached-exporter:v0.4.1

  ## Specify a imagePullPolicy
  ## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  # image_pull_policy: IfNotPresent

